version: '3.4'

services:    
    nginx:
        image: nginx:alpine
        working_dir: /var/www/html
        volumes: 
            - type: bind
              source: ./app/
              target: /var/www/html
            - ./logs/nginx/:/var/log/nginx/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8080:80'
        networks:
            - internal
        depends_on:
            - app

    postgres:
        image: postgres:13-alpine
        volumes: 
            - ./data/pg/db:/var/lib/postgresql/data
        networks:
            - internal
        ports:
            - '5432:5432'
        environment: 
            POSTGRES_DB: 'db_name'
            POSTGRES_USER: 'db_user'
            POSTGRES_PASSWORD: 'db_pass'

    redis:
        image: redis:alpine
        command: redis-server --bind redis
        volumes:
            - './data/redis/:/data'
        networks:
            - internal

    app:
        build: 
            context: .
            dockerfile: ./docker/php/dev/Dockerfile
        image: app_todo_test
        working_dir: /var/www/html
        volumes: 
            - type: bind
              source: ./app/
              target: /var/www/html
        networks: 
            - internal
        depends_on:
            - postgres
            - redis
        ports:
            - '10000:10001'
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1 remote_port=10001 idekey=Docker"
            PHP_IDE_CONFIG: "serverName=Docker"
    setup:
        image: app_todo_test:latest
        volumes: 
            - type: bind
              source: ./app/
              target: /var/www/html
        networks:
            - internal
        depends_on:
            - app
        command: >
            sh -c "[ ! -f ./.env.local ] && echo "APP_ENV=dev" > ./.env.local || echo "" &&
                    composer install &&
                    yarn install --force &&
                    yarn dev &&
                    composer dump-env dev &&
                    php bin/console cache:warmup &&
                    php bin/console assets:install --symlink --relative &&
                    php bin/console doctrine:migration:migrate --no-interaction"

networks: 
    internal:
        driver: bridge
        ipam:
            driver: default
            config: 
                - subnet: 192.168.220.0/28
